### ISSUE TITLE
How does your code run on Multi-GPUs

### ISSUE THREAD

**Issue by whu-zhigao** [Adam27X/hybrid_BC#3]
Hi @Adam27X ,

I run your code on a node which  equipped with 4 NVIDIA K20c GPUs.  The host machine is running RedHat OS version 4.4.5-6. The CUDA version is 9.0 using the “-arch=sm35” compute compatibility flag. But the algorithm just show 1 GPU is running. How can I run the code on multi-GPUs and how can I run the code on multi-node with multi-GPUs?

**Comment by Adam27X** [comment]
Hello,

Apologies for the late response here. Simply put the version of the code uploaded here only supports 1 GPU, as you found out. Porting this code to run on multiple GPUs is fairly straightforward using MPI. It was a long time ago at this point but I believe we didn't publish the multi-GPU version of the code on github because the build process was specifically tailored to our systems and wouldn't have been usable by others.
